name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
      
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2.14.3
      with:
        api-level: 29
        script: ./gradlew connectedCheck

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
